#############################################################################
# Makefile for building: GameForMeego02110707.app/Contents/MacOS/GameForMeego02110707
# Generated by qmake (2.01a) (Qt 4.7.3) on: Fri Jul 8 18:07:15 2011
# Project:  GameForMeego02110707.pro
# Template: app
# Command: /Users/tecton/QtSDK/Desktop/Qt/473/gcc/bin/qmake -spec ../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/macx-g++ -o Makefile GameForMeego02110707.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
INCPATH       = -I../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/macx-g++ -I. -I../../../QtSDK/Desktop/Qt/473/gcc/lib/QtCore.framework/Versions/4/Headers -I../../../QtSDK/Desktop/Qt/473/gcc/include/QtCore -I../../../QtSDK/Desktop/Qt/473/gcc/lib/QtGui.framework/Versions/4/Headers -I../../../QtSDK/Desktop/Qt/473/gcc/include/QtGui -I../../../QtSDK/Desktop/Qt/473/gcc/include -I. -I. -F/Users/tecton/QtSDK/Desktop/Qt/473/gcc/lib
LINK          = g++
LFLAGS        = -headerpad_max_install_names -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5
LIBS          = $(SUBLIBS) -F/Users/tecton/QtSDK/Desktop/Qt/473/gcc/lib -L/Users/tecton/QtSDK/Desktop/Qt/473/gcc/lib -framework QtGui -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /Users/tecton/QtSDK/Desktop/Qt/473/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		gamelocation.cpp \
		gameviewwidget.cpp \
		pixmapitem.cpp moc_mainwindow.cpp \
		moc_gameviewwidget.cpp \
		moc_pixmapitem.cpp \
		qrc_resource.cpp
OBJECTS       = main.o \
		mainwindow.o \
		gamelocation.o \
		gameviewwidget.o \
		pixmapitem.o \
		moc_mainwindow.o \
		moc_gameviewwidget.o \
		moc_pixmapitem.o \
		qrc_resource.o
DIST          = ../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/unix.conf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/mac.conf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/mac-g++.conf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/qconfig.pri \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_functions.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_config.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/exclusive_builds.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_pre.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/default_pre.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/dwarf2.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/debug.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_post.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/default_post.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/x86_64.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/objective_c.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/warn_on.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/unix/thread.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/moc.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/rez.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/sdk.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/resources.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/uic.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/yacc.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/lex.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/include_source_dir.prf \
		GameForMeego02110707.pro
QMAKE_TARGET  = GameForMeego02110707
DESTDIR       = 
TARGET        = GameForMeego02110707.app/Contents/MacOS/GameForMeego02110707

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-gdwarf-2 \
		-arch \
		x86_64 \
		-Xarch_x86_64 \
		-mmacosx-version-min=10.5 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile GameForMeego02110707.app/Contents/PkgInfo GameForMeego02110707.app/Contents/Resources/empty.lproj GameForMeego02110707.app/Contents/Info.plist $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) GameForMeego02110707.app/Contents/MacOS/ || $(MKDIR) GameForMeego02110707.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: GameForMeego02110707.pro  ../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/macx-g++/qmake.conf ../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/unix.conf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/mac.conf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/mac-g++.conf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/qconfig.pri \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_functions.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_config.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/exclusive_builds.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_pre.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/default_pre.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/dwarf2.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/debug.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_post.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/default_post.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/x86_64.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/objective_c.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/warn_on.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/unix/thread.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/moc.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/rez.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/sdk.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/resources.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/uic.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/yacc.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/lex.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec ../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/macx-g++ -o Makefile GameForMeego02110707.pro
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/unix.conf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/mac.conf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/mac-g++.conf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/qconfig.pri:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/modules/qt_webkit_version.pri:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_functions.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_config.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/exclusive_builds.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_pre.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/default_pre.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/dwarf2.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/debug.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_post.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/default_post.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/x86_64.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/objective_c.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/warn_on.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/unix/thread.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/moc.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/rez.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/sdk.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/resources.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/uic.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/yacc.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/lex.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec ../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/macx-g++ -o Makefile GameForMeego02110707.pro

GameForMeego02110707.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) GameForMeego02110707.app/Contents || $(MKDIR) GameForMeego02110707.app/Contents 
	@$(DEL_FILE) GameForMeego02110707.app/Contents/PkgInfo
	@echo "APPL????" >GameForMeego02110707.app/Contents/PkgInfo
GameForMeego02110707.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) GameForMeego02110707.app/Contents/Resources || $(MKDIR) GameForMeego02110707.app/Contents/Resources 
	@touch GameForMeego02110707.app/Contents/Resources/empty.lproj
	
GameForMeego02110707.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) GameForMeego02110707.app/Contents || $(MKDIR) GameForMeego02110707.app/Contents 
	@$(DEL_FILE) GameForMeego02110707.app/Contents/Info.plist
	@sed -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,GameForMeego02110707,g" -e "s,@TYPEINFO@,????,g" ../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/macx-g++/Info.plist.app >GameForMeego02110707.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/GameForMeego021107071.0.0 || $(MKDIR) .tmp/GameForMeego021107071.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/GameForMeego021107071.0.0/ && $(COPY_FILE) --parents mainwindow.h gamelocation.h gameviewwidget.h pixmapitem.h .tmp/GameForMeego021107071.0.0/ && $(COPY_FILE) --parents resource.qrc .tmp/GameForMeego021107071.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp gamelocation.cpp gameviewwidget.cpp pixmapitem.cpp .tmp/GameForMeego021107071.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/GameForMeego021107071.0.0/ && (cd `dirname .tmp/GameForMeego021107071.0.0` && $(TAR) GameForMeego021107071.0.0.tar GameForMeego021107071.0.0 && $(COMPRESS) GameForMeego021107071.0.0.tar) && $(MOVE) `dirname .tmp/GameForMeego021107071.0.0`/GameForMeego021107071.0.0.tar.gz . && $(DEL_FILE) -r .tmp/GameForMeego021107071.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r GameForMeego02110707.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp moc_gameviewwidget.cpp moc_pixmapitem.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_gameviewwidget.cpp moc_pixmapitem.cpp
moc_mainwindow.cpp: mainwindow.h
	/Users/tecton/QtSDK/Desktop/Qt/473/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ mainwindow.h -o moc_mainwindow.cpp

moc_gameviewwidget.cpp: pixmapitem.h \
		gamelocation.h \
		gameviewwidget.h
	/Users/tecton/QtSDK/Desktop/Qt/473/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ gameviewwidget.h -o moc_gameviewwidget.cpp

moc_pixmapitem.cpp: gamelocation.h \
		pixmapitem.h
	/Users/tecton/QtSDK/Desktop/Qt/473/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ pixmapitem.h -o moc_pixmapitem.cpp

compiler_rcc_make_all: qrc_resource.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resource.cpp
qrc_resource.cpp: resource.qrc \
		balls/yellow01.png \
		balls/blue01.png \
		balls/red01.png \
		balls/white01.png \
		balls/green01.png \
		balls/purple01.png
	/Users/tecton/QtSDK/Desktop/Qt/473/gcc/bin/rcc -name resource resource.qrc -o qrc_resource.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/Users/tecton/QtSDK/Desktop/Qt/473/gcc/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		gameviewwidget.h \
		pixmapitem.h \
		gamelocation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

gamelocation.o: gamelocation.cpp gamelocation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gamelocation.o gamelocation.cpp

gameviewwidget.o: gameviewwidget.cpp gameviewwidget.h \
		pixmapitem.h \
		gamelocation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gameviewwidget.o gameviewwidget.cpp

pixmapitem.o: pixmapitem.cpp pixmapitem.h \
		gamelocation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pixmapitem.o pixmapitem.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_gameviewwidget.o: moc_gameviewwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gameviewwidget.o moc_gameviewwidget.cpp

moc_pixmapitem.o: moc_pixmapitem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pixmapitem.o moc_pixmapitem.cpp

qrc_resource.o: qrc_resource.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resource.o qrc_resource.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/local/bin/ || $(MKDIR) $(INSTALL_ROOT)/usr/local/bin/ 
	$(DEL_FILE) -r "$(INSTALL_ROOT)/usr/local/bin/GameForMeego02110707.app"
	
	-$(INSTALL_DIR) "GameForMeego02110707.app" "$(INSTALL_ROOT)/usr/local/bin/GameForMeego02110707.app"

uninstall_target:  FORCE
	-$(DEL_FILE) -r "$(INSTALL_ROOT)/usr/local/bin/GameForMeego02110707.app"
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/local/bin/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

